// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: listings.sql

package db

import (
	"context"

	decimal "github.com/jackc/pgx-shopspring-decimal"
	"github.com/jackc/pgx/v5/pgtype"
)

const countListings = `-- name: CountListings :one
SELECT count(*)
FROM immo_listings
WHERE $1::varchar IS NULL OR search_path = $1
`

func (q *Queries) CountListings(ctx context.Context, searchPath pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countListings, searchPath)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteListing = `-- name: DeleteListing :exec
DELETE
FROM immo_listings
WHERE ad_id = $1
`

func (q *Queries) DeleteListing(ctx context.Context, adID string) error {
	_, err := q.db.Exec(ctx, deleteListing, adID)
	return err
}

const getListing = `-- name: GetListing :one
SELECT ad_id, vertical_id, ad_type_id, product_id, advert_status_id, advert_status, description, heading, property_type, rooms_layout, number_of_rooms, floor, address, location, district, state, country, postcode, latitude, longitude, living_area_sqm, usable_area_sqm, estate_size_sqm, price, price_display, price_per_sqm, rent_per_month, org_id, org_name, is_private, main_image, seo_url, published_at, attributes, search_path, first_seen_at, last_seen_at
FROM immo_listings
WHERE ad_id = $1
`

func (q *Queries) GetListing(ctx context.Context, adID string) (ImmoListing, error) {
	row := q.db.QueryRow(ctx, getListing, adID)
	var i ImmoListing
	err := row.Scan(
		&i.AdID,
		&i.VerticalID,
		&i.AdTypeID,
		&i.ProductID,
		&i.AdvertStatusID,
		&i.AdvertStatus,
		&i.Description,
		&i.Heading,
		&i.PropertyType,
		&i.RoomsLayout,
		&i.NumberOfRooms,
		&i.Floor,
		&i.Address,
		&i.Location,
		&i.District,
		&i.State,
		&i.Country,
		&i.Postcode,
		&i.Latitude,
		&i.Longitude,
		&i.LivingAreaSqm,
		&i.UsableAreaSqm,
		&i.EstateSizeSqm,
		&i.Price,
		&i.PriceDisplay,
		&i.PricePerSqm,
		&i.RentPerMonth,
		&i.OrgID,
		&i.OrgName,
		&i.IsPrivate,
		&i.MainImage,
		&i.SeoUrl,
		&i.PublishedAt,
		&i.Attributes,
		&i.SearchPath,
		&i.FirstSeenAt,
		&i.LastSeenAt,
	)
	return i, err
}

const listListings = `-- name: ListListings :many
SELECT ad_id, vertical_id, ad_type_id, product_id, advert_status_id, advert_status, description, heading, property_type, rooms_layout, number_of_rooms, floor, address, location, district, state, country, postcode, latitude, longitude, living_area_sqm, usable_area_sqm, estate_size_sqm, price, price_display, price_per_sqm, rent_per_month, org_id, org_name, is_private, main_image, seo_url, published_at, attributes, search_path, first_seen_at, last_seen_at
FROM immo_listings
WHERE $1::varchar IS NULL OR search_path = $1
ORDER BY last_seen_at DESC, ad_id
LIMIT $3 OFFSET $2
`

type ListListingsParams struct {
	SearchPath pgtype.Text `db:"search_path" json:"search_path"`
	Offset     int32       `db:"offset" json:"offset"`
	Limit      int32       `db:"limit" json:"limit"`
}

func (q *Queries) ListListings(ctx context.Context, arg ListListingsParams) ([]ImmoListing, error) {
	rows, err := q.db.Query(ctx, listListings, arg.SearchPath, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ImmoListing
	for rows.Next() {
		var i ImmoListing
		if err := rows.Scan(
			&i.AdID,
			&i.VerticalID,
			&i.AdTypeID,
			&i.ProductID,
			&i.AdvertStatusID,
			&i.AdvertStatus,
			&i.Description,
			&i.Heading,
			&i.PropertyType,
			&i.RoomsLayout,
			&i.NumberOfRooms,
			&i.Floor,
			&i.Address,
			&i.Location,
			&i.District,
			&i.State,
			&i.Country,
			&i.Postcode,
			&i.Latitude,
			&i.Longitude,
			&i.LivingAreaSqm,
			&i.UsableAreaSqm,
			&i.EstateSizeSqm,
			&i.Price,
			&i.PriceDisplay,
			&i.PricePerSqm,
			&i.RentPerMonth,
			&i.OrgID,
			&i.OrgName,
			&i.IsPrivate,
			&i.MainImage,
			&i.SeoUrl,
			&i.PublishedAt,
			&i.Attributes,
			&i.SearchPath,
			&i.FirstSeenAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertListing = `-- name: UpsertListing :exec
INSERT INTO immo_listings (ad_id,
                            vertical_id,
                            ad_type_id,
                            product_id,
                            advert_status_id,
                            advert_status,
                            description,
                            heading,
                            property_type,
                            rooms_layout,
                            number_of_rooms,
                            floor,
                            address,
                            location,
                            district,
                            state,
                            country,
                            postcode,
                            latitude,
                            longitude,
                            living_area_sqm,
                            usable_area_sqm,
                            estate_size_sqm,
                            price,
                            price_display,
                            price_per_sqm,
                            rent_per_month,
                            org_id,
                            org_name,
                            is_private,
                            main_image,
                            seo_url,
                            published_at,
                            attributes,
                            search_path)
VALUES ($1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8,
        $9,
        $10,
        $11,
        $12,
        $13,
        $14,
        $15,
        $16,
        $17,
        $18,
        $19,
        $20,
        $21,
        $22,
        $23,
        $24,
        $25,
        $26,
        $27,
        $28,
        $29,
        $30,
        $31,
        $32,
        $33,
        $34,
        $35)
ON CONFLICT (ad_id) DO UPDATE SET vertical_id      = excluded.vertical_id,
                                   ad_type_id       = excluded.ad_type_id,
                                   product_id       = excluded.product_id,
                                   advert_status_id = excluded.advert_status_id,
                                   advert_status    = excluded.advert_status,
                                   description      = excluded.description,
                                   heading          = excluded.heading,
                                   property_type    = excluded.property_type,
                                   rooms_layout     = excluded.rooms_layout,
                                   number_of_rooms  = excluded.number_of_rooms,
                                   floor            = excluded.floor,
                                   address          = excluded.address,
                                   location         = excluded.location,
                                   district         = excluded.district,
                                   state            = excluded.state,
                                   country          = excluded.country,
                                   postcode         = excluded.postcode,
                                   latitude         = excluded.latitude,
                                   longitude        = excluded.longitude,
                                   living_area_sqm  = excluded.living_area_sqm,
                                   usable_area_sqm  = excluded.usable_area_sqm,
                                   estate_size_sqm  = excluded.estate_size_sqm,
                                   price            = excluded.price,
                                   price_display    = excluded.price_display,
                                   price_per_sqm    = excluded.price_per_sqm,
                                   rent_per_month   = excluded.rent_per_month,
                                   org_id           = excluded.org_id,
                                   org_name         = excluded.org_name,
                                   is_private       = excluded.is_private,
                                   main_image       = excluded.main_image,
                                   seo_url          = excluded.seo_url,
                                   published_at     = excluded.published_at,
                                   attributes       = excluded.attributes,
                                   search_path      = excluded.search_path,
                                   last_seen_at     = now()
`

type UpsertListingParams struct {
	AdID           string             `db:"ad_id" json:"ad_id"`
	VerticalID     int32              `db:"vertical_id" json:"vertical_id"`
	AdTypeID       int32              `db:"ad_type_id" json:"ad_type_id"`
	ProductID      int32              `db:"product_id" json:"product_id"`
	AdvertStatusID string             `db:"advert_status_id" json:"advert_status_id"`
	AdvertStatus   string             `db:"advert_status" json:"advert_status"`
	Description    string             `db:"description" json:"description"`
	Heading        pgtype.Text        `db:"heading" json:"heading"`
	PropertyType   pgtype.Text        `db:"property_type" json:"property_type"`
	RoomsLayout    pgtype.Text        `db:"rooms_layout" json:"rooms_layout"`
	NumberOfRooms  *decimal.Decimal   `db:"number_of_rooms" json:"number_of_rooms"`
	Floor          pgtype.Int4        `db:"floor" json:"floor"`
	Address        pgtype.Text        `db:"address" json:"address"`
	Location       pgtype.Text        `db:"location" json:"location"`
	District       pgtype.Text        `db:"district" json:"district"`
	State          pgtype.Text        `db:"state" json:"state"`
	Country        pgtype.Text        `db:"country" json:"country"`
	Postcode       pgtype.Text        `db:"postcode" json:"postcode"`
	Latitude       pgtype.Float8      `db:"latitude" json:"latitude"`
	Longitude      pgtype.Float8      `db:"longitude" json:"longitude"`
	LivingAreaSqm  pgtype.Int4        `db:"living_area_sqm" json:"living_area_sqm"`
	UsableAreaSqm  pgtype.Int4        `db:"usable_area_sqm" json:"usable_area_sqm"`
	EstateSizeSqm  pgtype.Int4        `db:"estate_size_sqm" json:"estate_size_sqm"`
	Price          *decimal.Decimal   `db:"price" json:"price"`
	PriceDisplay   pgtype.Text        `db:"price_display" json:"price_display"`
	PricePerSqm    *decimal.Decimal   `db:"price_per_sqm" json:"price_per_sqm"`
	RentPerMonth   *decimal.Decimal   `db:"rent_per_month" json:"rent_per_month"`
	OrgID          pgtype.Text        `db:"org_id" json:"org_id"`
	OrgName        pgtype.Text        `db:"org_name" json:"org_name"`
	IsPrivate      bool               `db:"is_private" json:"is_private"`
	MainImage      pgtype.Text        `db:"main_image" json:"main_image"`
	SeoUrl         string             `db:"seo_url" json:"seo_url"`
	PublishedAt    pgtype.Timestamptz `db:"published_at" json:"published_at"`
	Attributes     []byte             `db:"attributes" json:"attributes"`
	SearchPath     pgtype.Text        `db:"search_path" json:"search_path"`
}

func (q *Queries) UpsertListing(ctx context.Context, arg UpsertListingParams) error {
	_, err := q.db.Exec(ctx, upsertListing,
		arg.AdID,
		arg.VerticalID,
		arg.AdTypeID,
		arg.ProductID,
		arg.AdvertStatusID,
		arg.AdvertStatus,
		arg.Description,
		arg.Heading,
		arg.PropertyType,
		arg.RoomsLayout,
		arg.NumberOfRooms,
		arg.Floor,
		arg.Address,
		arg.Location,
		arg.District,
		arg.State,
		arg.Country,
		arg.Postcode,
		arg.Latitude,
		arg.Longitude,
		arg.LivingAreaSqm,
		arg.UsableAreaSqm,
		arg.EstateSizeSqm,
		arg.Price,
		arg.PriceDisplay,
		arg.PricePerSqm,
		arg.RentPerMonth,
		arg.OrgID,
		arg.OrgName,
		arg.IsPrivate,
		arg.MainImage,
		arg.SeoUrl,
		arg.PublishedAt,
		arg.Attributes,
		arg.SearchPath,
	)
	return err
}
